drop table config if exists;
create table config(
	id bigint generated by default as identity,
	cron varchar(40),
	creator varchar(40),
	primary key(id)
);

/*
CREATE TABLE `quartz`.`config`  (
	`id` bigint(0) NOT NULL AUTO_INCREMENT,
	`cron` varchar(255) NULL,
	`creator` varchar(255) NULL,
	PRIMARY KEY (`id`)
);*/
